### ISSUE TITLE
Add addressfinder widget on profile tab

### ISSUE THREAD

**Issue by ghost** [rainlab/userplus-plugin#25]
The user+ plugin rely on the excellent [location plugin](https://octobercms.com/plugin/rainlab-location) in order to manage user address. That's great.

However, it's a shame to not use the addressfinder widget provided by the plugin in order to provide a convenient way to search an address and automatically populate related fields.

In addition, that addressfinder widget can also populate latitude and longitude fields that would allow to display a map of all your users, it would be a great addition too.

To resume, I suggest that user+ plugin would use the full potential of location plugin by adding addressfinder, latitude and longitude fields. You could answer that I can write a plugin to extend user+, but creating a plugin to extend a plugin that already extend another one is a little cumbersome to me.

I could create a PR if the idea is accepted.

Best regards,

Alex

**Comment by LukeTowers** [comment]
@Alex360hd this plugin is mostly just meant as an example for how to extend plugins. I don't really want to get into adding all sorts of bells and whistles to it since that's within the purview of other, more specific plugins to handle. Extending a plugin that extends another plugin is no different than just extending a plugin by itself in the first place.
